---
repos:
  - repo: https://github.com/homebysix/pre-commit-macadmin
    # rev: v1.10.1
    hooks:
      - id: check-autopkg-recipes
        args: ["--recipe-prefix=com.github.jgstew.", "--strict", "--"]
      - id: forbid-autopkg-overrides
